### ISSUE TITLE
Stock go back when status is on-hold

### ISSUE THREAD

**Issue by uiliw** [jamesgol/woocommerce-cart-stock-reducer#17]
When you add the product to cart, the virtual stock get reduced, ok, when you choose payment method its still reduced, put when you actually pay, sometimes the gateway take a while to process payment and your status goes to on-hold.. at this time, the virtual stock goes back to normal(because there is no item in your cart anymore) and meanwhile some one can purchase and you who is still waiting for the gateway to be concluded loose you the product because someone payment process was faster than yours...

what i suggest is that virtual stock only goes back to normal after the status actually changes to precessing.. where this will actually reduce the real stock..

**Comment by jamesgol** [comment]
That is an interesting problem, I'll have to think about this some more.

**Comment by uiliw** [comment]
do u have any idea for a quick fix for now?? cause i have it up and running and already getting problems on the store... and unfortunetlly i cant shut it now
i did all the test before but in sandbox, and was all ok, but sandbox dont simulate on-hold so i didndt see this cenario..

**Comment by jamesgol** [comment]
Sorry I do not have any idea, it's probably going to be more complicated than a simple fix.  I will fit in some time when I get a chance but it has to contend with all of the other volunteer projects I work on.

**Comment by jamesgol** [comment]
Someone posted a similar issue here: https://wordpress.org/support/topic/it-seems-that-2-or-3-people-can-still-buy-at-the-same-time?replies=4#post-8099825

At first I didn't think they were similar because you said the status was changing to on-hold, but on further digging that should only be happening in some unique situations.  I did run some tests and it appears that it is very likely the same issue.  So right now I'd recommend setting the expire time to 3 hours which is the same as the paypal token expiration time.

When I can fit it in my schedule I'll work on some code to optionally update the expiration time to 3 hours if paypal is used.  Once the checkout is kicked over to them we don't get anything back unless they cancel the transation or complete it.

**Comment by jamesgol** [comment]
After some further testing I was able to keep a paypal cart "active" by refreshing it every 5 minutes, in my manual tests the carts timeout after 10 minutes of activity.  I've had this cart "active" for 6 hours now.

There must be some other mechanisms in play as well since I have seen (in other unrelated software), items remaining in a paypal cart after significant times.

More research is necessary.  I wish paypal would allow passing in a required time to checkout/expire but I have yet to discover anything like that.

**Comment by uiliw** [comment]
Thanks @jamesgol !

Well, i think you have to consider other gateways too, not only paypal. Im my case im using a brazilian service to process the payments, Pagseguro ([https://pagseguro.uol.com.br/](https://pagseguro.uol.com.br/)), and for sure pagseguro do not pass any required time to checkout/expire, like many other gateways, and what i said before is what happens.. sometimes takes 1min to process the payment, sometimes it takes 5 to 11hours and mostly of the times is right away witch is good.

Im setting the expiration time to 12hours propositaly because we want the customer to be able to do a "reservation" of that product for 12 hours (im my case its a bed from a room or a camping spot in a hotel). And If for any reason the customer decide to pay 11hours later, after the "reservation", he will have less than a hour to conclude his payment, and if his payment get **on-hold** for more than a hour, the stock will be free for any other to reserve/buy it, causing some frustrating situation.

So i don't think its a good idea to depend from the gateway but from **WC status**. 

When the payment is being validated on that gateway, the status on WC goes to **on-hold** and at this time the stock goes back so anyone can buy it too....  

I still think the best solution would be that virtual stock only goes back to normal after the status on WC actually changes to **precessing** where WC received from the gateway that it has been payed successfully and this will actually reduce the real stock.. And when the status goes to **on-hold**, it should ignore the expiration time and still keep the virtual cart active until change the status to **processing** or **canceled/failed**. If the status on WC get **canceled/failed**, because of a bad payment or canceled by the user, the virtual stock goes back to normal and the customer or any other would have to "reserve" the product again (if the expiration time is out already).

**Comment by jamesgol** [comment]
You're right, I definitely don't want to go down the path of having a hack for each gateway.  When I have some free time I'll have to do more testing and see what I can come up with.

**Comment by jamesgol** [comment]
I just committed a change that should help with your situation, though it is something that will require a custom function on your side.

```
add_filter( 'wc_csr_expire_ignore_status', 'jmg_wc_csr_expire_ignore_status', 10, 4 );

function jmg_wc_csr_expire_ignore_status( $default, $status, $time, $order_id ) { 
        return array( 'wc-on-hold' );
}
```

This would allow any order status in that array (default is empty array) to be automatically skipped from expiration check.  I decided to have the order status, expiration time, and order id passed along to the filter in case you wanted to make adjust the behavior based on how old the order is.

It's a pretty complicated situation and something that will likely be unique to each persons setup.

There is still a potential TODO related to this.  If someone has an order in one of those states and it is expired the message displayed is 'Please checkout within 0 Seconds to guarantee your items don't expire.'

**Comment by bruno-rodrigues** [comment]
What about increasing (or reseting) the timer when the status changes to `wc-on-hold`?
This would help in the situation @uiliw mentioned above:

> Im setting the expiration time to 12hours propositaly because we want the customer to be able to do a "reservation" of that product for 12 hours (im my case its a bed from a room or a camping spot in a hotel). And **If for any reason the customer decide to pay 11hours later, after the "reservation", he will have less than a hour to conclude his payment**, and if his payment get on-hold for more than a hour, the stock will be free for any other to reserve/buy it, causing some frustrating situation.


One more thing:

The following code will never get hit:

```
if ( null !== $order_awaiting_payment && ( $order = new WC_Order( $order_awaiting_payment ) ) ) {
			// If a session is marked with an Order ID in 'order_awaiting_payment' check the status to decide if we should skip the expiration check
			if ( in_array( $order->post_status, apply_filters( 'wc_csr_expire_ignore_status', $this->ignore_status, $order->post_status, $expire_time, $order_awaiting_payment ) ) ) {
				return false;
			}
		}
```

because `order_awaiting_payment` session variable in cleared in [class-wc-cart](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-cart.php#L300l).

We must find another way to get the order and use the `wc_csr_expire_ignore_status` filter as we was supposed to do.

As soon as I come up with a possible solution I'll update this thread.
