### ISSUE TITLE
Disable Cart Stock Reducer on some products

### ISSUE THREAD

**Issue by mathildesp** [jamesgol/woocommerce-cart-stock-reducer#32]
Is it possible to disable cart stock reducer on some product and keep it on others? I sell limited edition print which need the time expiration and some prints which don't need it. Is there a way to do this? Thank you

**Comment by jamesgol** [comment]
Your situation isn't something I've heard anyone asking about.  Do you require most of your items to have an expiration or no expiration?

It's been a while since I tested those situations, but I know I added a distinct post_meta field (configurable via filter 'wc_csr_expire_custom_key', but by default its 'csr_expire_time') that allows adjusting specific expiration times.

So if you want most items to expire but certain items to not expire you set that specific post_meta field to 'never' and those items won't expire, if you want the inverse you should be able to set the global expiration time to never and then set specific times for each item.

**Comment by mathildesp** [comment]
Yes, most of my items need an expiration, just few of them don't need it.
I will try that, thank you.
Edit : It's worked well!
