### ISSUE TITLE
N+1 problem

### ISSUE THREAD

**Issue by mboisvertdupras** [jamesgol/woocommerce-cart-stock-reducer#66]
First of all, I just want to say we love this plugin and it works well for our use case, thank you! This is more of an observation rather than an issue but perhaps it can open up discussion on the problem.

It seems like the plugin has an n+1 problem wherein the number of queries executed on a page load is proportional to the number of items displayed. Using Query Monitor we can see that for each product, duplicated queries are being executed. On a busy site with lots of products, this can inflate the total number of queries executed on page load to over 1,000+ which affects performance drastically.

**Comment by jamesgol** [comment]
With WooCommerce < 3.x it was about n+1, but with > 3.x it is far worse than that since they changed the way the filters that are used work.  The development version has some major improvements but I have not had available time to test for backwards compatibility so I have not made an official release yet.

**Comment by mboisvertdupras** [comment]
That's good to know, thank you for the quick response. Is this repository the development version of the plugin?

**Comment by jamesgol** [comment]
Yes the development version is here.  I always have good intentions of devoting some time here but actual paid projects always end up taking over time.
